# Generated by Django 4.2.9 on 2024-02-28 20:53

from django.db import migrations, models
import django_summernote.utils


class Migration(migrations.Migration):

    dependencies = [
        ("django_summernote", "0002_update-help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                max_length=1000, upload_to=django_summernote.utils.uploaded_filepath
            ),
        ),
    ]
